/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-misused-promises */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */

import Head from 'next/head';
import { useState } from 'react';
import { ChatMessage } from '~/components/ChatMessage';
import { MessageInput } from '~/components/MessageInput';

export interface ChatMessageProps {
  id: string;
  role: string;
  content: string;
  model?: string;
}

export default function Home() {
  const [messages, setMessages] = useState<ChatMessageProps[]>([]);

  async function handleNewMessage(content: string) {
    const role = 'user';
    const sendMessages = [
      ...messages,
      { id: Math.random().toString(36).substring(2, 15), role, content },
    ];
    setMessages(sendMessages);

    const response = await fetch('/api/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ messages: sendMessages }),
    });

    if (response.body) {
      const reader = response.body.getReader();
      const decoder = new TextDecoder('utf-8');

      const newBotMessage: ChatMessageProps = {
        id: Math.random().toString(36).substring(2, 15),
        role: 'assistant',
        content: '',
      };

      while (true) {
        const { value, done } = await reader.read();
        if (done) break;

        const messageText = decoder.decode(value);
        newBotMessage.content += messageText;

        // there may be a JSON object at the beginning of the message, which contains the model name (streaming workaround)
        if (!newBotMessage.model && newBotMessage.content.startsWith('{')) {
          const endOfJson = newBotMessage.content.indexOf('}');
          if (endOfJson > 0) {
            const json = newBotMessage.content.substring(0, endOfJson + 1);
            try {
              const parsed = JSON.parse(json);
              newBotMessage.model = parsed.model;
              newBotMessage.content = newBotMessage.content.substring(
                endOfJson + 1
              );
            } catch (e) {
              // error parsing JSON, ignore
              console.log(e);
            }
          }
        }

        setMessages((list) => {
          // find the message to update with new text tokens.
          const message = list.find(
            (message) => message.id === newBotMessage.id
          );

          // update the message with the new text content, re-render the message-list anyway if the message couldn't be found.
          return !message ? [...list, newBotMessage] : [...list];
        });
      }
    }
  }

  return (
    <>
      <Head>
        <title>AskIT</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex h-full w-full flex-col items-center gap-2 px-8 pt-4">
          <h1 className="self-center font-black text-white">AskIT</h1>
          <h6 className="self-center italic text-white">
            Powered by gpt-3.5-turbo
          </h6>
        </div>
        <div className="h-full w-[700px] min-w-max max-w-[800px] shrink justify-end rounded-md border-2 border-solid border-gray-500 bg-slate-800">
          <div className="flex h-[500px] flex-col gap-4 overflow-y-auto p-4">
            <ChatMessage
              id="0"
              role="assistant"
              content="Hejsan! Vad kan jag hjälpa dig med idag?"
            />
            {messages.map(({ id, role, content }) => (
              <ChatMessage key={id} id={id} role={role} content={content} />
            ))}
          </div>

          <MessageInput onSend={handleNewMessage} />
        </div>
      </main>
    </>
  );
}
