import { type NextPage } from "next";
import Head from "next/head";
import ChatMessage from "~/components/ChatMessage";
import MessageForm from "~/components/MessageForm";

const messages = [
  { type: "user", content: "Jag vill ha hjälp med att få igång min VPN." },
  { type: "assistant", content: "Okej! Sitter du på Mac eller Windows?" },
  { type: "user", content: "Det vill inte jag berätta för dig." },
  { type: "assistant", content: "Okej :( Vad taskigt..." },
  { type: "user", content: "Okej då :) Jag sitter på Mac." },
  { type: "assistant", content: ":)" },
  { type: "user", content: ":)" },
];

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>AskIT</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex h-full w-full flex-col items-center gap-2 px-8 pt-4">
          <h1 className="self-center font-black text-white">AskIT</h1>
          <h6 className="self-center italic text-white">
            Powered by gpt-3.5-turbo
          </h6>

          <div className="h-full w-[800px] justify-end rounded-md border-2 border-solid border-gray-500 bg-slate-800">
            <div className="flex h-[500px] flex-col gap-4 overflow-y-auto p-4">
              <ChatMessage
                type="assistant"
                content="Hejsan! Vad kan jag hjälpa dig med idag?"
              />

              {messages.map(({ type, content }) => (
                <ChatMessage key={type} type={type} content={content} />
              ))}
            </div>

            <div className="h-auto w-full place-self-end bg-slate-700">
              <MessageForm />
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
