import type { NextApiRequest, NextApiResponse } from 'next';

export default function retrieval(req: NextApiRequest, res: NextApiResponse) {
  console.log(req);
  const context =
    'Title: Installera/ansluta till VPN-klienten - Windows (Personal) url: https://serviceportalen.lnu.se/sv-se/article/1290271 content: Se maskinöversättning på  Språk Språk printreply Installera/ansluta till VPN-klienten - Windows (Personal) Senast uppdaterad  6 mars 2023 Denna guide beskriver hur du installerar och ansluter till Linnéuniversitetets nätverk via en VPN-klient på en dator med Windows. VPN använder du när du befinner dig utanför universitetet för att komma åt tjänster på samma sätt som om du vore på universitetet.   OBS! Från och med den 2 maj 2023 behöver alla anställda och användare med  externkonton logga in med MFA (multifaktorautentisering) vid anslutning via VPN. Mer information på Medarbetare Inloggningen via VPN ändras. Installera VPN-klienten via webb-VPN Du kan själv installera VPN-klienten genom att logga in på Webb-VPN med ditt Personal- eller Externkonto enligt instruktionerna nedan. Logga in på Webb-VPN (https://vpn.lnu.se) med ditt Personal- eller Externkonto.  Om du har registrerat ditt konto för MFA-inloggning behöver du även ange en engångskod. Mer information om MFA.   På sidan som öppnas när du är inloggad, klicka på länken Start AnyConnect.   Klicka på Download for Windows.   Välj att spara filen i mappen ”Den här datorn/Hämtade filer” (This PC/Downloads), och klicka på Spara.   Sök fram filen där du sparade ner den och dubbelklicka på den för att starta installationen.  Klicka på Next.   Markera ”I accept …” och klicka på Next.   Klicka på Install.   Klicka Ja (Yes) i meddelat ”Tillåter du att den här appen från en okänd utgivare får göra ändringar på enheten?”   Installationen startar, när den är klar klicka på Finish.   VPN-klienten ”Cisco AnyConnect” har nu installerats.  Se guiden nedan hur du ansluter till Lnu:s nätverk. Ansluta med VPN-klienten Guide hur du ansluter via VPN när du har VPN-klienten installerad. Klicka på Windows Sök nere till höger i aktivitetslisten, skriv in ”Cisco” och klicka på Cisco AnyConnect Secure Mobility Client.   I rutan som öppnas skriver du in vpn.lnu.se och klickar på Connect.   Ange följande uppgifter i inloggningsrutan, klicka sen på OK. Group: Employee Username: Användarnamnet till ditt personalkonto/externkonto Password: Lösenordet till ditt personalkonto/externkonto   Om du har registrerat ditt konto för MFA-inloggning behöver du även ange en engångskod och klicka Continue.   Om du inte har registrerat ditt konto för MFA-inloggning, klicka OK på informationsrutan om MFA som visas. Mer information om MFA.  Ett meddelande visas när du är ansluten. Koppla från VPN-anslutningen Klicka på pilen nere till höger i aktivitetslisten och sen på Cisco AnyConnect ikonen.   Klicka på Disconnect för att avsluta din VPN-anslutning.';

  res.status(200).json(context);
}
